### ISSUE TITLE
Setting the default approach doesn't work

### ISSUE THREAD

**Issue by ErykCh** [codelion/optillm#69]
Hi,

my configuration for mcts is as follows:

in docker-compose.yml

```
services:
  optillm:
  container_name: optillm-proxy
  image: optillm:1.0
  ports:
  - 81:8000
  restart: unless-stopped
  environment:
  - OPENAI_API_KEY=no_key
  command: --log debug --approach mcts --n 5 --simulations 3 --depth 3 --return-full-response true --base-url http://vllm:8000/v1
```

I would expect that if I do not specify slug in the model name or in the promt, mcts will be selected, because I have:
--approach mcts

Starting logs:
2024-10-21 10:09:24,593 - INFO - Starting server with approach: mcts
2024-10-21 10:09:24,594 - INFO - Server configuration: {'approach': 'mcts', 'mcts_simulations': 2, 'mcts_exploration': 0.2, 'mcts_depth': 1, 'best_of_n': 3, 'rstar_max_depth': 3, 'rstar_num_rollouts': 5, 'rstar_c': 1.4, 'n': 5, 'base_url': 'http://vllm:8000/v1', 'optillm_api_key': '', 'return_full_response': True, 'port': 8000, 'log': 'debug', 'simulations': 3, 'exploration': 0.2, 'depth': 3}

Prompt:

2024-10-21 10:09:44,412 - INFO - Received request to /v1/chat/completions
2024-10-21 10:09:44,412 - DEBUG - Intercepted Bearer Token: my_key
2024-10-21 10:09:44,412 - DEBUG - Request data: {'model': '<cut>', 'user': '66f282757cce4320b5e6bfa1', 'stream': True, 'messages': [{'role': 'user', 'content': '<cut>'}]}
2024-10-21 10:09:44,472 - INFO - Using approach(es) ['bon'], operation SINGLE, with model <cut>

but should use mcts
